name: ExploBattle2
author: NBSgamesAT
api-version: 1.19
version: 1.0
main: at.nbsgames.explobattle.Main

commands:
  explobattle:
    usage: /eb <subcommand>
    description: Handles explobattles, manages arenas.
  eb:
    usage: /eb <subcommands>
    description: Short version of /explobattle